ProjetoFinanceiro.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectFinance.Infrastructure.Repositories;
using ProjectFinance.Web.Models;
using System.Net.Http;
using System.Text;

namespace ProjectFinance.Web.Controllers
{
    public class ClientController : Controller
    {
        #region Props/ID

        private readonly string _endpoint;

        private readonly HttpClient _httpClient;

        private readonly IConfiguration _configuration;

        private readonly IRepositoryClient _clientRepository;

        #endregion Propriedades

        #region Constructor

        public ClientController(IConfiguration configuration)
        {
            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            _endpoint = _configuration["AppConfig:EndPoints:Url_Api"];

            _httpClient = new HttpClient
            {
                BaseAddress = new Uri(_endpoint)
            };
        }

        #endregion

        #region Index

        public async Task<IActionResult> Index()
        {
            try
            {
                List<ClientViewModel> clients = null;

                HttpResponseMessage response = await _httpClient.GetAsync(_endpoint);
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    clients = JsonConvert.DeserializeObject<List<ClientViewModel>>(content);
                }
                else
                {
                    ModelState.AddModelError(null, "Error processing request");
                }

                return View(clients);
            }
            catch (Exception ex)
            {
                string message = ex.Message;
                throw;
            }
        }

        #endregion

        #region Get

        public async Task<IActionResult> Get(int id)
        {
            try
            {
                ClientViewModel result = await Search(id);
                return View(result);
            }
            catch (Exception)
            {
                throw;
            }
        }

        #endregion

        #region Create

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name, Cpf")] ClientViewModel client)
        {
            try
            {
                string json = JsonConvert.SerializeObject(client);
                byte[] buffer = Encoding.UTF8.GetBytes(json);
                ByteArrayContent byteArrayContent = new ByteArrayContent(buffer);
                byteArrayContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                string url = _endpoint;
                TempData["SuccessMessage"] = "Client successfully created!";
                HttpResponseMessage response = await _httpClient.PostAsync(url, byteArrayContent);

                if (!response.IsSuccessStatusCode)
                    ModelState.AddModelError(null, "Error processing request");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["ErroMessage"] = $"Oops! We could not create the Client, please try again, error detail:  ERROR";
                throw;
            }
        }

        #endregion

        #region Edit

        public async Task<IActionResult> Edit(int id)
        {
            ClientViewModel client = await Search(id);
            return View(client);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("ClientId, Name, Cpf")] ClientViewModel client)
        {
            try
            {
                string json = JsonConvert.SerializeObject(client);
                byte[] buffer = Encoding.UTF8.GetBytes(json);
                ByteArrayContent byteArrayContent = new ByteArrayContent(buffer);
                byteArrayContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                string url = _endpoint;
                TempData["SuccessMessage"] = "Client successfully edited!";
                HttpResponseMessage response = await _httpClient.PutAsync(url, byteArrayContent);

                if (!response.IsSuccessStatusCode)
                    ModelState.AddModelError(null, "Error processing request");

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["ErroMessage"] = $"Oops! We could not edit the Client, please try again!!";
                throw;
            }
        }

        #endregion

        #region Delete

        public async Task<IActionResult> Delete(int id)
        {
            ClientViewModel client = await Search(id);
            if (client == null)
                return NotFound();

            return View(client);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string ClientId)
        {
            int id = Int32.Parse(ClientId);
            string url = $"{_endpoint}{id}";
            TempData["SuccessMessage"] = "Client successfully deleted!";
            HttpResponseMessage response = await _httpClient.DeleteAsync(url);

            if (!response.IsSuccessStatusCode)
            {
                TempData["ErroMessage"] = $"Oops! We could not delete the client, please try again!!";
                ModelState.AddModelError(null, "Erro ao processar a solicitação");
            }

            return RedirectToAction("Index");
        }

        #endregion

        #region Helpers

        private async Task<ClientViewModel> Search(int id)
        {
            try
            {
                ClientViewModel result = null;
                string url = $"{_endpoint}{id}";
                HttpResponseMessage response = await _httpClient.GetAsync(url);
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<ClientViewModel>(content);
                }

                return result;
            }
            catch (Exception)
            {
                throw;
            }
        }

        #endregion MétodosAuxiliares
    }
}

ProjetoFinanceiro.Web/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectFinance.Web.Models.DTO;

namespace ProjectFinance.Web.Controllers
{
    public class PeopleController : Controller
    {
        #region Props

        private static List<DtoPeople> _people;

        #endregion

        #region Constructor

        public PeopleController()
        {
            if (_people == null)
            {
                SeedingPeople();
            }
        }

        #endregion

        #region Helpers/Population
        private void SeedingPeople()
        {
            _people = new List<DtoPeople>
            {
                    new DtoPeople
                    {
                    Id = Guid.NewGuid().ToString(),
                    Name = "Lucas Ribeirao Preto",
                    Email = "lucas@gmail.com"
                },
                new DtoPeople
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = "Grindwald Harry Potter",
                    Email = "hp@hotmail.com"
                },
                new DtoPeople
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = "Woldemort Harry Potter",
                    Email = "whp@outlook.com"
                }
            };
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            return View(_people);
        }

        #endregion

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Name, Email")] DtoPeople person)
        {
            try
            {
                person.Id = Guid.NewGuid().ToString();
                _people.Add(person);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
        }

        #endregion

        #region Delete

        [HttpGet]
        public IActionResult DeletePage(string id)
        {
            DtoPeople people = _people.FirstOrDefault(p => p.Id.Equals(id));

            return View(people);
        }

        [HttpPost]
        public IActionResult DeleteReal(string Id)
        {
            DtoPeople people = _people.FirstOrDefault(p => p.Id.Equals(Id));

            if (people != null) _people.Remove(people);

            return RedirectToAction("Index");
        }

        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(string id)
        {
            DtoPeople pessoa = _people.FirstOrDefault(p => p.Id.Equals(id));
            return View(pessoa);
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id, Name, Email")] DtoPeople person)
        {
            DtoPeople pessoaPesquisa = _people.FirstOrDefault(p => p.Id.Equals(person.Id));
            if (pessoaPesquisa != null)
            {
                _people.Remove(pessoaPesquisa);
                _people.Add(person);
            }

            return RedirectToAction("Index");
        }

        #endregion

        #region Details

        [HttpGet]
        public IActionResult Details(string id)
        {
            DtoPeople person = _people.FirstOrDefault(p => p.Id.Equals(id));
            return View(person);
        }

        #endregion
    }
}

ProjetoFinanceiro.Web/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Project Finance";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--Jquery DataTables-->
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet"/>
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectFinance.Web.styles.css" asp-append-version="true" />
 

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project Finance Web
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Jquery DataTables-->
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>